---
title: "Post-Impute"
author: "Mari Johnson"
date: "12/10/2022"
output: html_document
---

 Updates October:
 - Re-indexed and merged bcf files to get a more stringent R2
 - Making separate typhoid, para and merged plink files


```{r setup, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
knitr::opts_knit$set(root.dir = '~/GWAS_22/gwas_final/meta')
#Assoc folder switched to after merging
```
```{r Set up, eval=TRUE}
library(data.table)
library(stringr)
library(dplyr)
library(plinkQC)
library(tidylog)
library(janitor)
```

### Check Merge .fam IDs

```{r Tidy-fam-IID, eval = FALSE}
fam <- fread("merged_data.fam")
# Clean IID col to match ID in covar files
fam2 <- fam
fam2$V2 <-  str_remove_all(fam$V2, "^([0-9]+_)")
update_ids <- bind_cols(fam$V1, fam$V2, fam2$V1, fam2$V2)

write.table(update_ids, "update_ids.txt", col.names = F, row.names = F, quote = F, sep = '\t')
system("plink --bfile merged_data --update-ids update_ids.txt --make-bed --out merge_rn")
#TODO let plink2 know about error
```

#### Update covar and pheno files

**Key**
Strain: C, P = 3, T = 1, TN = 2
Sex M=1, F=2
Re-challenge N=1, PP=2, PT=3, TP=4, TT=5
Vaccine: NONE = 0, Ty21a = 1, M01ZH09= 2, Vi-PS = 3, Vi-TT= 4

```{r typhoid}
'%!in%' <- function(x,y)!('%in%'(x,y))
# covar checks -----------------------------------------------------------------
# New fam file -re filtered R2
fam <- fread("~/GWAS_22/gwas_final//merge/merge_rn.fam")
covar <- fread("~/GWAS_22/new_gwas/meta/final_metadata/all_covar_june.txt")
# Tidy covar table
covar$chall_vax <- str_c(covar$Challenge, covar$Vaccine, sep = "_")
covar <- clean_names(covar)
covar <- covar %>% dplyr::rename(IID = iid)

# Filter for serovars
covar_typhoid <- covar %>% filter(challenge != 3, re_challenge  != 5) #259
covar_para <- covar %>% filter(challenge == 3, re_challenge  != 2) #71
covar_enteric <- covar %>% filter(re_challenge == 1)  # 312
```

```{r check-missing}
# Check for missing samples ----------------------------------------------------
fam <- fam %>% rename(IID = V2)
new_covar <- left_join(fam, covar, by = "IID")
# missing samples
missing <- filter(new_covar, is.na(study))
# Make new IID col to match old IIDs 'Genotyping ID'
missing$IID_2 <- str_remove_all(missing$IID, "^([0-9]+-)")
```

```{r Tidy-missing}
 # Tidy old covar files---------------------------------------------------------
check <- fread("~/GWAS_22/new_gwas/meta/covar.txt")
#pheno2 <- fread("~/GWAS_22/new_gwas/meta/pheno.txt")
#covar2 <- left_join(pheno2, covar2, by ="GENOTYPING_ID")
#rm(pheno2)
check <- rename(check, IID = GENOTYPING_ID)
# Look in old covar for IIDs that are in our missing IIDs
check <- filter(check, IID %in% missing$IID_2)
check <-  distinct(check) %>% filter(!is.na(Study))
# Found 5 samples :) with diagnosis info

# Tidy colnames/vars so can rejoin----------------------------------------------
check$Vaccine <- ifelse(check$Vaccine == "None",0,
                            ifelse(check$Vaccine == "Ty21a",1,
                                   ifelse(check$Vaccine == "M01ZH09", 2,
                                          ifelse(check$Vaccine == "Vi-PS", 3,
                                                 ifelse(check$Vaccine == "Vi-TT", 4,NA)))))
#Recode strain, sex challenge
check$Challenge <- ifelse(check$Challenge == "P", 3, ifelse(check$Challenge == "T", 1, NA))
check$Sex <- ifelse(check$Sex == "M", 1, ifelse(check$Sex == "F", 2, NA))
check$Re_Challenge <- as.numeric(str_replace_all(check$Re_Challenge, "N", "1"))
check$Chall_Vax <- str_c(covar$Challenge, covar$Vaccine, sep = "_")
check <- clean_names(check)
check <- rename(check, IID_2 = iid) # will match IID_2 in missing then tidy
```
```{r Rejoin and remake tables}
# Rejoin -----------------------------------------------------------------------
missing <- missing %>% select(IID, IID_2)
missing <- left_join(missing, check, by = "IID_2") %>% filter(!is.na(study)) %>% select(-IID_2)

#add back to covar
covar <- bind_rows(covar, missing)
#check samples again
test <- anti_join(fam, covar, by = "IID") # 4 missing covars so improved :)

covar_typhoid <- covar %>% filter(challenge != 3, re_challenge  != 5) #263
covar_para <- covar %>% filter(challenge == 3, re_challenge  != 2) #72
covar_enteric <- covar %>% filter(re_challenge == 1)  #317
```

```{r Get-phenodata}
pheno <- fread("~/GWAS_22/new_gwas/meta/final_metadata/all_pheno_num.txt")
pheno <-  filter(pheno, IID %in% covar$IID) # 342

covar_typhoid <- left_join(covar_typhoidpheno, by="IID")
covar_para <- left_join(covar_para,pheno, by="IID")
covar_enteric <- left_join(covar_enteric,pheno, by="IID")
```

```{r Extra PATCH samples}
# Check what fam IDs are in covar_typhoid
test <- filter(fam, IID %in% covar_typhoid$IID)# 255 #redo = 260 :)
# Check what covar_typhoid IIDs are not in test IIDs
patch <- filter(covar_typhoid, IID %!in% test$IID) 
# test <- filter(patch, IID %in% fam$IID) # 5 extra samples
# just need to remove _PATCH string from covar file so it will match fam IID

# Missex samples ---------------------------------------------------------------

missex <- fread("fail_sexcheck.txt")
missex <- missex[,V2]
covar_typhoid <- covar_typhoid %>% filter(IID %!in% missex)

# Make new tables
covar_typhoid$IID <- str_remove_all(covar_typhoid$IID, "_PATCH")

load(file = "id_covars.RData")

# Get FID back
fam <-  fam %>% select(V1, IID) %>% rename(FID = V1) #254
covar_typhoid <- inner_join(fam, covar_typhoid, by = "IID")
# Filter duplicates
covar_typhoid <- filter(covar_typhoid, stri_duplicated(IID)==FALSE) %>%
  select(-ethnicity)

# Recode vars (plink2 can use categorical)
covar_typhoid$vaccine <- ifelse(covar_typhoid$vaccine == 0,"None",
                            ifelse(covar_typhoid$vaccine == 1,"Ty21a",
                                   ifelse(covar_typhoid$vaccine == 2, "M01ZH09",
                                          ifelse(covar_typhoid$vaccine ==  3,"Vi-PS",
                                                 ifelse(covar_typhoid$vaccine == 4,"Vi-TT",NA)))))


#C, P = 3, T = 1, TN = 2
covar_typhoid$challenge <- as.factor(covar_typhoid$challenge)
levels(covar_typhoid$challenge) <- c("T", "TN")

covar_typhoid$re_challenge  <- as.factor(covar_typhoid$re_challenge)
levels(covar_typhoid$re_challenge) <- c("N", "PT")

covar_typhoid$chall_vax <- str_c(covar_typhoid$challenge, covar_typhoid$vaccine, sep = "x")

# Missing pheno data -----------------------------------------------------------
missing_p <- filter(covar_typhoid, is.na(Diagnosed))
p_data <- fread("pheno_fix.txt") #added zeros back in to IIDs where needed
p_data <- filter(p_data, IID %in% missing_p$IID)
rm(missing_p)

covar_typhoid <- covar_typhoid %>% left_join(p_data, by= "IID") %>%
  mutate(Diagnosed = coalesce(Diagnosed.x, Diagnosed.y))
covar_typhoid <- select(covar_typhoid, -c(Diagnosed.x, Diagnosed.y, place_of_birth))

# Make pheno and keep files ----------------------------------------------------
pheno_typhoid <- covar_typhoid %>% select(FID, IID, Diagnosed)
keep_t <- select(covar_typhoid, FID, IID)

write.table(keep_t, file="keep_t.txt", col.names = T, row.names = F, quote = F, sep = '\t')
write.table(covar_typhoid, file="covar_typhoid.txt",col.names = T, row.names = F, quote = F, sep = '\t')
write.table(pheno_typhoid, file="pheno_typhoid.txt", col.names = T, row.names = F, quote = F, sep = '\t')

#TODO paratyphoid files
```
```{r pca}
fam <- fread("~/GWAS_22/gwas_final/merge/typhoid/QC/typhoid2.IBD.fam") # 251
pca <- fread("~/GWAS_22/gwas_final/merge/typhoid/QC/pca/typhoid2.LD.eigenvec") # 251
test <- pca %>% filter(IID %in% covar_typhoid$IID) #250
# remake typhoid files
save.image(file = "id_covars.RData")
```

```{bash filter-mergern}
plink --bfile /home/mari/GWAS_22/gwas_final/merge/merge_rn \
--keep /home/mari/GWAS_22/gwas_final/meta/keep_t.txt \
--make-bed \
--out /home/mari/GWAS_22/gwas_final/merge/typhoid/typhoid2
# 253 participants
```
